In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Reload all modules imported with %aimport
%load_ext autoreload
%autoreload 1

In [3]:
import numpy as np
import pandas as pd

In [47]:
a1 = np.arange(2*3).reshape(2,3)
b1 = np.array([10,20]).reshape(2,1)
a1
b1
a1 * b1

a2 = np.arange(20, 20 + 2*3).reshape(2,3)
b2 = np.array([100,200]).reshape(2,1)
a2
b2
a2 * b2

array([[0, 1, 2],
       [3, 4, 5]])

array([[10],
       [20]])

array([[  0,  10,  20],
       [ 60,  80, 100]])

array([[20, 21, 22],
       [23, 24, 25]])

array([[100],
       [200]])

array([[2000, 2100, 2200],
       [4600, 4800, 5000]])

In [48]:
astf = np.vstack([a1,a2])
bstf = np.vstack([b1,b2])
abstf = astf * bstf
abstf
abstf.reshape(2,2, 3)

array([[   0,   10,   20],
       [  60,   80,  100],
       [2000, 2100, 2200],
       [4600, 4800, 5000]])

array([[[   0,   10,   20],
        [  60,   80,  100]],

       [[2000, 2100, 2200],
        [4600, 4800, 5000]]])

In [51]:
ast = np.vstack( [ a1[np.newaxis, ...], a2[np.newaxis, ...] ] )
bst = np.vstack( [ b1[np.newaxis, ...], b2[np.newaxis, ...] ] )
ast
bst
ast * bst
(ast * bst).shape

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[20, 21, 22],
        [23, 24, 25]]])

array([[[ 10],
        [ 20]],

       [[100],
        [200]]])

array([[[   0,   10,   20],
        [  60,   80,  100]],

       [[2000, 2100, 2200],
        [4600, 4800, 5000]]])

(2, 2, 3)